# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "jupyter",
# META     "jupyter_kernel_name": "python3.11"
# META   },
# META   "dependencies": {}
# META }

# CELL ********************

%pip install ms-fabric-cli --quiet

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "jupyter_python"
# META }

# MARKDOWN ********************

# # ✅ Prerequisites for Gateway Monitoring
# 
# This document outlines the required setup to enable the **Gateway Monitoring** solution, which collects and reports health and activity data from the **On-Premises Data Gateway**.
# 
# ---
# 
# ## 🧩 1. Gateway Monitoring Solution Overview
# 
# The Gateway Monitoring solution is composed of:
# - A **PowerShell script** installed and executed on the **On-Premises Data Gateway**
# - A **Fabric notebook** that generates the base configuration used by the script
# - Secure authentication using a **service principal**
# 
# The PowerShell script is responsible for sending heartbeat and reporting information, while the notebook simplifies initial configuration.
# 
# ---
# 
# ## 🔐 2. Service Principal Requirements
# 
# A **service principal (SP)** is required to authenticate against Microsoft Fabric.
# 
# The service principal **must** meet all the following conditions:
# - ✅ Have **Fabric Admin API access**
# - ✅ Be a **Member of the Fabric workspace** used by the solution
# - ✅ Be an **Administrator of the On-Premises Data Gateway**
# 
# Without these permissions, the monitoring solution will not be able to retrieve metadata or report gateway status.
# 
# ---
# 
# ## 🖥️ 3. Install the PowerShell Script on the On-Premises Data Gateway
# 
# - The **Gateway Monitoring PowerShell script** must be installed on the machine hosting the **On-Premises Data Gateway**.
# - The script runs locally and is responsible for:
#   - Sending **heartbeat signals**
#   - Sending **gateway monitoring reports**
#   - Respecting the configuration values generated by the notebook
# 
# Ensure the script runs under an identity that has access to the generated configuration file.
# 
# ---
# 
# ## 📓 4. Generate the Base Configuration Using the Notebook
# 
# Running the **current notebook** will automatically generate the **base configuration file** required by the PowerShell script.
# 
# This file defines how the Gateway Monitoring process behaves and how often data is sent.
# 
# ---
# 
# ## ⚙️ 5. Configure Gateway Monitoring Variables
# 
# After the configuration file is created, you must review and update the following variables as needed:
# 
# - **HeartbeatEnable**  
#   Enable or disable the gateway heartbeat.
# 
# - **HeartbeatInterval**  
#   Interval (in seconds) at which heartbeat signals are sent.
# 
# - **ReportSendInterval**  
#   Interval (in seconds) at which monitoring reports are sent.
# 
# - **ReportRetention**  
#   Retention period (in days) for monitoring reports.
# 
# - **TenantId**  
#   Tenant ID of the service principal.
# 
# - **AppId**  
#   Application (Client) ID of the service principal.
# 
# These values control both authentication and the operational behavior of the monitoring process.
# 
# ---
# 
# ## 🧠 Why This Setup Matters
# 
# This configuration ensures:
# - ✅ Secure authentication using a service principal
# - ✅ Continuous visibility into gateway health
# - ✅ Configurable heartbeat and reporting intervals
# - ✅ Centralized monitoring aligned with Fabric governance
# 
# ---
# 
# ## ✅ Final Checklist
# 
# Before enabling Gateway Monitoring, confirm the following:
# 
# - ✔️ Service principal has **Fabric Admin API access**
# - ✔️ Service principal is **Workspace Member**
# - ✔️ Service principal is **Gateway Admin**
# - ✔️ PowerShell script is installed on the **On-Premises Data Gateway**
# - ✔️ Notebook has been executed to generate the base config file
# - ✔️ Gateway Monitoring variables are correctly configured
# 
# 🚀 Once completed, the Gateway Monitoring solution will begin reporting gateway health and activity based on the configured intervals.
# 
# ---
# 
# ## 📘 Learn More
# 
# For additional details and official guidance on platform monitoring, visit:
# 
# 👉 **https://aka.ms/fabric-platform-monitoring**
# 
# Look for the **Gateway** section for in-depth information specific to gateway monitoring and observability.


# CELL ********************

HeartbeatEnable = True
HeartbeatInterval = 1
ReportSendInterval = 5
ReportRetention = 10
TenatId = ""
AppId = ""

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "jupyter_python"
# META }

# CELL ********************

import subprocess
import yaml
import sempy.fabric as fabric
import json

heartbeat_eventsteam = "GatewayMonitoringHeartbeat.Eventstream"
report_eventstream = "GatewayMonitoringReports.Eventstream"

# Set environment parameters for Fabric CLI
token = notebookutils.credentials.getToken('pbi')
os.environ['FAB_TOKEN'] = token
os.environ['FAB_TOKEN_ONELAKE'] = token

def run_fab_command( command, capture_output: bool = False, silently_continue: bool = False):
    result = subprocess.run(["fab", "-c", command], capture_output=capture_output, text=True)
    if (not(silently_continue) and (result.returncode > 0 or result.stderr)):
       raise Exception(f"Error running fab command. exit_code: '{result.returncode}'; stderr: '{result.stderr}'")    
    if (capture_output): 
        output = result.stdout.strip()
        return output

def fab_get_id(name):
    id = run_fab_command(f"get /{workspace_name}.Workspace/{name} -q id" , capture_output = True, silently_continue= True)
    return(id)

def fab_get_item(name):
    item = run_fab_command(f"get /{workspace_name}.Workspace/{name}" , capture_output = True, silently_continue= True)
    return(item)

def fab_list_item():
    items = run_fab_command(f"ls /{workspace_name}.Workspace" , capture_output = True, silently_continue= True)
    return(items)

def fab_get_display_name(name):
    display_name = run_fab_command(f"get /{workspace_name}.Workspace/{name} -q displayName" , capture_output = True, silently_continue= True)
    return(display_name)

def fab_get_kusto_query_uri(name):
    connection = run_fab_command(f"get /{workspace_name}.Workspace/{name} -q properties.queryServiceUri", capture_output = True, silently_continue= True)
    return(connection)

def fab_get_kusto_ingest_uri(name):
    connection = run_fab_command(f"get /{workspace_name}.Workspace/{name} -q properties.ingestionServiceUri", capture_output = True, silently_continue= True)
    return(connection)

def fab_get_folders():
    response = run_fab_command(f"api workspaces/{workspace_id}/folders", capture_output = True, silently_continue= True)
    return(json.loads(response).get('text',{}).get('value',[]))

def fab_get_folder(folder_name):
    for f in fab_get_folders():
        if f.get('displayName') == folder_name:
            return f
    return None

def fab_assign_item_folder(item_id,folder):
    folder_details = fab_get_folder(folder)

    if folder_details is None:
        payload = json.dumps({"displayName": folder})
        folder_details = run_fab_command(f"api -X post workspaces/{workspace_id}/folders -i {payload}", capture_output = True, silently_continue= True)
        folder_details = json.loads(folder_details).get('text',{})

    payload = json.dumps({"folder": folder_details.get('id')})

    return run_fab_command(f"api -X patch workspaces/{workspace_id}/items/{item_id} -i {payload}", capture_output = True, silently_continue= True)


workspace_id = fabric.get_notebook_workspace_id()
workspace_name = fabric.list_workspaces(filter=f"id eq '{workspace_id}'")['Name'][0]

heartbeat_id = fab_get_id(heartbeat_eventsteam)
report_id = fab_get_id(report_eventstream)

heartbeat_conn_id = json.loads(run_fab_command(f"api workspaces/{workspace_id}/eventstreams/{heartbeat_id}/topology" , capture_output = True, silently_continue= True)).get("text",{}).get("sources",[])[0].get('id')
report_conn_id = json.loads(run_fab_command(f"api workspaces/{workspace_id}/eventstreams/{report_id}/topology" , capture_output = True, silently_continue= True)).get("text",{}).get("sources",[])[0].get('id')

heartbeat_connection = json.loads(run_fab_command(f"api workspaces/{workspace_id}/eventstreams/{heartbeat_id}/sources/{heartbeat_conn_id}/connection" , capture_output = True, silently_continue= True)).get("text",{}).get('accessKeys',{}).get('primaryConnectionString')
report_connection = json.loads(run_fab_command(f"api workspaces/{workspace_id}/eventstreams/{report_id}/sources/{report_conn_id}/connection" , capture_output = True, silently_continue= True)).get("text",{}).get('accessKeys',{}).get('primaryConnectionString')

GatewayLogUploadConfig = {
    "GatewayId": "",
    "GatewayLogsPath": ["C:\Windows\ServiceProfiles\PBIEgwService\AppData\Local\Microsoft\On-premises data gateway"],      
    "RootPath": "raw",
    "OutputPath": ".\data",
    "HeartbeatEnable": HeartbeatEnable,
    "HeartbeatInterval": HeartbeatInterval,
    "ReportSendInterval": ReportSendInterval,
    "ReportRetention": ReportRetention,
    "VerboseLogSendInterval": 600,
    "ServicePrincipal": {
        "TennatId": TenatId,
        "AppId": AppId,
        "SecretText": "",
    },
    "EventHubs": {
        "UploadReports": True,
        "ConnectionStrings": [
                {
                        "Report": "Heartbeat",
                        "EventHubConnectionString": heartbeat_connection
                },
                {
                        "Report": "Reports",
                        "EventHubConnectionString": report_connection
                }
        ]
    },
    "Lakehouse": {
        "UploadReports": False,
        "UploadLogs": False,
        "WorkspaceName": "",
        "LakehouseName": "",        
    },
    "ConnectionProperties": {
        "MaximumRetryCount": 3,
        "RetryIntervalSec": 1
    }
}

out_file = open("./builtin/config.json", "w")

json.dump(obj=GatewayLogUploadConfig,fp=out_file,indent=6)

out_file.close()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "jupyter_python"
# META }
